"""Central configuration for the healthcare AI repository analysis.

Every magic number, date bound, path and category list used by the dashboard,
the chart notebook and the refresh pipeline lives here. Nothing downstream
should hardcode a year, a threshold or a filename.

Date bounds deliberately are NOT hardcoded: they are derived from the data at
runtime (see `healthcare_ai.data.as_of` and `chart_year_range`). The only fixed
year here is CHART_START_YEAR, which is an editorial choice about how far back
the published charts look.
"""

from pathlib import Path

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent

# Seed dataset. Curated by hand (category / subcategory / standard are editorial
# judgements). Treated as an input to this pipeline, not an output of it.
HEALTHCARE_DATA_CSV = ROOT / "healthcare_data.csv"

# Generated by `healthcare_ai.github_api` (see refresh.py step 1).
REPOS_CLASSIFIED_CSV = ROOT / "repos_classified.csv"
REPOS_CLASSIFIED_ORGS_CSV = ROOT / "repos_classified_organizations.csv"
REPOS_CLASSIFIED_PERSONAL_CSV = ROOT / "repos_classified_personal.csv"

# Generated by `healthcare_ai.github_api` (see refresh.py step 2).
CONTRIBUTOR_STATS_CSV = ROOT / "contributor_detailed_stats.csv"
CONTRIBUTOR_STATS_AGG_CSV = ROOT / "contributor_detailed_stats_aggregated.csv"

# Generated by `healthcare_ai.stars` (see refresh.py step 3).
STAR_EVENTS_CSV = ROOT / "star_events_history.csv"

# Owner taxonomy, hand-maintained. See healthcare_ai/owner_types.py.
OWNER_TYPES_YAML = Path(__file__).resolve().parent / "owner_types.yaml"

# Chart output directory.
PLOTS_DIR = ROOT / "nice_plots"

# --------------------------------------------------------------------------
# Data processing
# --------------------------------------------------------------------------

# A repo counts as "Active" if it received a commit within this many days of
# the as-of date. Note this is measured against the data's own most recent
# commit, not wall-clock time, so a stale dataset does not silently drift
# towards "everything is inactive".
ACTIVITY_WINDOW_DAYS = 365

# Categories dropped from all analysis -- they are link collections and docs,
# not software projects.
EXCLUDED_CATEGORIES = (
    "Lists",
    "Tutorials",
    "Specification / Docs",
    "Archived / Deprecated",
    "Educational",
)

# Buckets for the "when was this repo created" cohort column. Each entry is
# (inclusive_start_year, label); the final bucket runs to the present. Labels
# are generated for the open-ended bucket so they never go stale.
CREATED_YEAR_BUCKETS = (
    (0, "Up to 2016"),
    (2016, "2016-2018"),
    (2019, "2019-2021"),
    (2022, None),  # label generated as "2022-<latest year in data>"
)

# --------------------------------------------------------------------------
# Charts
# --------------------------------------------------------------------------

# Published charts start here. The upper bound is always derived from the data
# (see data.chart_year_range) so a refresh never silently drops the new year.
CHART_START_YEAR = 2020

# The four-way ownership taxonomy that the ownership charts break out.
# Repos that fall outside these (coarse "Organization"/"User" from the GitHub
# API) are excluded from those specific charts.
CHART_OWNER_TYPES = (
    "Research Lab",
    "Community Project/Non-Profit",
    "Startup",
    "Incumbent",
)

# --------------------------------------------------------------------------
# Star history
# --------------------------------------------------------------------------

# Star history is fetched only for the top N repos by stars -- the stargazers
# API is one request per 100 stars, so the full set is not affordable.
STAR_HISTORY_TOP_N = 100

# Categories included in star history analysis. These must match the values in
# healthcare_data.csv exactly (they are case-sensitive).
STAR_HISTORY_CATEGORIES = (
    "Interoperability",
    "Infrastructure",
    "Model Development",
    "HAI engineering",
    "Archived",
)

# --------------------------------------------------------------------------
# GitHub API
# --------------------------------------------------------------------------

GITHUB_API_BASE = "https://api.github.com"

# Seconds to sleep between API calls.
RATE_LIMIT_DELAY = 0.1

# Seconds to back off when the API returns 403 (rate limited).
RATE_LIMIT_BACKOFF = 60

# Results per page for paginated endpoints (GitHub max is 100).
PER_PAGE = 100

# Bot accounts excluded from contributor rankings.
BOT_ACCOUNTS = (
    "dependabot",
    "dependabot[bot]",
    "dependabot-preview[bot]",
    "github-actions[bot]",
    "renovate[bot]",
    "greenkeeper[bot]",
    "imgbot[bot]",
    "allcontributors[bot]",
    "semantic-release-bot",
    "snyk-bot",
    "codecov[bot]",
    "netlify[bot]",
    "whitesource-bolt-for-github[bot]",
)

# --------------------------------------------------------------------------
# Data quality thresholds (enforced by tests/)
# --------------------------------------------------------------------------

# Fail the test suite if more than this share of repos have no entry in
# owner_types.yaml. This is the signal that the taxonomy needs attention after
# a refresh -- see REFRESH.md.
MAX_UNCLASSIFIED_OWNER_SHARE = 0.60
